"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Generic, Optional, Sequence, Tuple, TypeVar


KT = TypeVar("KT")
VT = TypeVar("VT")
@dataclass
class ConsumerRecord(Generic[KT, VT]):
    topic: str
    partition: int
    offset: int
    timestamp: int
    timestamp_type: int
    key: Optional[KT]
    value: Optional[VT]
    checksum: Optional[int]
    serialized_key_size: int
    serialized_value_size: int
    headers: Sequence[Tuple[str, bytes]]
    ...
